### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by ImSaravanakrish**

### CODE REVIEW

**Comment by dragonempire117** [comment]
@saravanakrish97 Lol 🙃

**Comment by anilchauhanxda** [comment]
@saravanakrish97 Who did this? @Unknownanime007 is this you bish

**Comment by anilchauhanxda** [comment]
@saravanakrish97 @am_Tanny delete this trash pull request

**Comment by AmTanny** [comment]
@saravanakrish97 Tf?

**Comment by JayPatel1314** [comment]
Tanny bro u r great

**Comment by AmTanny** [comment]
@JayPatel1314 abbe bsdk

**Pull request closed without merging**
